// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
"use strict";

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var State$ReactTemplate = require("./State.bs.js");

var component = ReasonReact.statelessComponent("AddInput");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */ 9] = function() {
    return ReasonReact.element(
      /* None */ 0,
      /* None */ 0,
      Curry._1(
        State$ReactTemplate.Context[/* Consumer */ 5][/* make */ 1],
        function(param) {
          var send = param[/* send */ 0];
          return React.createElement(
            "button",
            {
              onClick: function() {
                return Curry._1(send, /* AddTodo */ 0);
              }
            },
            "Add"
          );
        }
      )
    );
  };
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
