// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
"use strict";

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Input$ReactTemplate = require("./Input.bs.js");
var State$ReactTemplate = require("./State.bs.js");
var AddInput$ReactTemplate = require("./AddInput.bs.js");
var TodoList$ReactTemplate = require("./TodoList.bs.js");

var component = ReasonReact.statelessComponent("App");

var component$1 = ReasonReact.statelessComponent("TestComponent");

function make() {
  var newrecord = component$1.slice();
  newrecord[/* render */ 9] = function() {
    console.log("Initial Render");
    return React.createElement(
      "div",
      undefined,
      ReasonReact.element(
        /* None */ 0,
        /* None */ 0,
        Input$ReactTemplate.make(/* array */ [])
      ),
      ReasonReact.element(
        /* None */ 0,
        /* None */ 0,
        AddInput$ReactTemplate.make(/* array */ [])
      ),
      ReasonReact.element(
        /* None */ 0,
        /* None */ 0,
        TodoList$ReactTemplate.make(/* array */ [])
      )
    );
  };
  return newrecord;
}

var TestComponent = /* module */ [/* component */ component$1, /* make */ make];

function make$1() {
  var newrecord = component.slice();
  newrecord[/* render */ 9] = function() {
    return ReasonReact.element(
      /* None */ 0,
      /* None */ 0,
      State$ReactTemplate.make(
        /* array */ [
          ReasonReact.element(/* None */ 0, /* None */ 0, make(/* array */ []))
        ]
      )
    );
  };
  return newrecord;
}

exports.component = component;
exports.TestComponent = TestComponent;
exports.make = make$1;
/* component Not a pure module */
