// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
"use strict";

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var State$ReactTemplate = require("./State.bs.js");

var component = ReasonReact.statelessComponent("Input");

function handleChange(send, e) {
  return Curry._1(send, /* ChangeInput */ Block.__(0, [e.target.value]));
}

function make() {
  var newrecord = component.slice();
  newrecord[/* render */ 9] = function() {
    return ReasonReact.element(
      /* None */ 0,
      /* None */ 0,
      Curry._1(
        State$ReactTemplate.Context[/* Consumer */ 5][/* make */ 1],
        function(param) {
          var send = param[/* send */ 0];
          return React.createElement("input", {
            value: param[/* state */ 1][/* input */ 1],
            onChange: function(param) {
              return handleChange(send, param);
            }
          });
        }
      )
    );
  };
  return newrecord;
}

exports.component = component;
exports.handleChange = handleChange;
exports.make = make;
/* component Not a pure module */
