// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
"use strict";

var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Theme$ReactTemplate = require("./Theme.bs.js");

var component = ReasonReact.statelessComponent("background");

function make(children) {
  var newrecord = component.slice();
  newrecord[/* render */ 9] = function() {
    return ReasonReact.element(
      /* None */ 0,
      /* None */ 0,
      Curry._1(
        Theme$ReactTemplate.Context[/* Consumer */ 5][/* make */ 1],
        function(theme) {
          var match = +(theme === /* Light */ 0);
          return ReasonReact.createDomElement(
            "div",
            {
              className: match !== 0 ? "background-light" : "background-dark"
            },
            children
          );
        }
      )
    );
  };
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
