// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
"use strict";

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var App$ReactTemplate = require("./App.bs.js");

ReactDOMRe.renderToElementWithId(
  ReasonReact.element(
    /* None */ 0,
    /* None */ 0,
    App$ReactTemplate.make(/* array */ [])
  ),
  "index"
);

/*  Not a pure module */
