// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
"use strict";

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Theme$ReactTemplate = require("./Theme.bs.js");
var Title$ReactTemplate = require("./Title.bs.js");
var Background$ReactTemplate = require("./Background.bs.js");

var component = ReasonReact.reducerComponent("App");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */ 9] = function(param) {
    var send = param[/* send */ 3];
    var state = param[/* state */ 1];
    return React.createElement(
      "div",
      {
        className: "App"
      },
      ReasonReact.element(
        /* None */ 0,
        /* None */ 0,
        Curry._2(
          Theme$ReactTemplate.Context[/* Provider */ 4][/* make */ 1],
          /* Some */ [state[/* theme */ 0]],
          /* array */ [
            ReasonReact.element(
              /* None */ 0,
              /* None */ 0,
              Background$ReactTemplate.make(
                /* array */ [
                  React.createElement(
                    "button",
                    {
                      onClick: function() {
                        var match = +(state[/* theme */ 0] === /* Dark */ 1);
                        return Curry._1(
                          send,
                          /* ChangeTheme */ [
                            match !== 0 ? /* Light */ 0 : /* Dark */ 1
                          ]
                        );
                      }
                    },
                    "Toggle Theme"
                  ),
                  ReasonReact.element(
                    /* None */ 0,
                    /* None */ 0,
                    Title$ReactTemplate.make("Reason Context", /* array */ [])
                  )
                ]
              )
            )
          ]
        )
      )
    );
  };
  newrecord[/* initialState */ 10] = function() {
    return /* record */ [/* theme : Light */ 0];
  };
  newrecord[/* reducer */ 12] = function(action, _) {
    return /* Update */ Block.__(0, [/* record */ [/* theme */ action[0]]]);
  };
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
