// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
"use strict";

var ReasonReactContext = require("reason-react-context/src/ReasonReactContext.bs.js");

var Context = ReasonReactContext.CreateContext(
  /* module */ [/* name */ "Theme", /* defaultValue : Light */ 0]
);

exports.Context = Context;
/* Context Not a pure module */
