// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
"use strict";

var ReasonReact = require("reason-react/src/ReasonReact.js");

var passThrough = props => props.children;

function make(children) {
  return ReasonReact.wrapJsForReason(passThrough, {}, children);
}

exports.passThrough = passThrough;
exports.make = make;
/* passThrough Not a pure module */
