// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
"use strict";

var Jest = require("@glennsl/bs-jest/src/jest.js");

describe("sample test", function() {
  return Jest.test("1 == 1", function() {
    return Jest.Expect[/* toBe */ 2](1, Jest.Expect[/* expect */ 0](1));
  });
});

/*  Not a pure module */
